export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

export const GET_PROFILE_START = "GET_PROFILE_START";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const GET_PROFILE_HANDLE_START = "GET_PROFILE_HANDLE_START";
export const GET_PROFILE_HANDLE_SUCCESS = "GET_PROFILE_HANDLE_SUCCESS";
export const GET_PROFILE_HANDLE_FAIL = "GET_PROFILE_HANDLE_FAIL";

export const CREATE_PROFILE_START = "CREATE_PROFILE_START";
export const CREATE_PROFILE_SUCCESS = "CREATE_PROFILE_SUCCESS";
export const CREATE_PROFILE_FAIL = "CREATE_PROFILE_FAIL";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";

export const GET_PROFILES_START = "GET_PROFILES_START";
export const GET_PROFILES_SUCCESS = "GET_PROFILES_SUCCESS";
export const GET_PROFILES_FAIL = "GET_PROFILES_FAIL";

//export const DELETE_PROFILE = "DELETE_PROFILE";
export const DELETE_PROFILE_START = "DELTE_PROFILE_START";
export const DELETE_PROFILE_SUCCESS = "DELTE_PROFILE_SUCCESS";
export const DELETE_PROFILE_FAIL = "DELTE_PROFILE_FAIL";

//add experience actions
export const ADD_EXPERIENCE_START = "ADD_EXPERIENCE_START";
export const ADD_EXPERIENCE_SUCCESS = "ADD_EXPERIENCE_SUCCESS";
export const ADD_EXPERIENCE_FAIL = "ADD_EXPERIENCE_FAIL";

//delete experience actions
export const DELETE_EXPERIENCE_START = "DELETE_EXPERIENCE_START";
export const DELETE_EXPERIENCE_SUCCESS = "DELETE_EXPERIENCE_SUCCESS";
export const DELETE_EXPERIENCE_FAIL = "DELETE_EXPERIENCE_FAIL";

//add education actions
export const ADD_EDUCATION_START = "ADD_EDUCATION_START";
export const ADD_EDUCATION_SUCCESS = "ADD_EDUCATION_SUCCESS";
export const ADD_EDUCATION_FAIL = "ADD_EDUCATION_FAIL";

//delete education actions
export const DELETE_EDUCATION_START = "DELETE_EDUCATION_START";
export const DELETE_EDUCATION_FAIL = "DELETE_EDUCATION_FAIL";
export const DELETE_EDUCATION_SUCCESS = "DELETE_EDUCATION_SUCCESS";

export const ERROR = "ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

//post actions

export const POST_LOADING = "POST_LOADING";

export const GET_POST = "GET_POST";
export const GET_POST_FAIL = "GET_POST_FAIL";

export const GET_POSTS = "GET_POSTS";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";

export const ADD_POST = "ADD_POST";
export const ADD_POST_FAIL = "ADD_POST_FAIL";

export const DELETE_POST = "DELETE_POST";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export const LIKE_POST = "LIKE_POST";
export const LIKE_POST_FAIL = "LIKE_POST_FAIL";

export const UNLIKE_POST = "UNLIKE_POST";
export const UNLIKE_POST_FAIL = "UNLIKE_POST_FAIL";
